steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_SERVICE_NAME}:latest'
    id: 'push-image-latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1000m'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=3000'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},GOOGLE_CLOUD_REGION=${_REGION},NODE_ENV=production,ENVIRONMENT=${_ENVIRONMENT}'
      - '--timeout=300'
    id: 'deploy-to-cloud-run'

  # Step 4: Verify deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'describe'
      - '${_SERVICE_NAME}'
      - '--region=${_REGION}'
      - '--format=get(status.url)'
    id: 'verify-deployment'

# Timeout for the entire build
timeout: 1200s

# Build options
options:
  machineType: 'E2_STANDARD_4'
  logging: CLOUD_LOGGING_ONLY

# Substitution variables
substitutions:
  _REGION: 'asia-northeast1'
  _SERVICE_NAME: 'gameday-console-prod'
  _DOCKER_REPO: 'gameday-console-docker'
  _ENVIRONMENT: 'prod'

# Images to be pushed to registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPO}/${_SERVICE_NAME}:latest'